# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: <img class="avatar" />
email: fabio@fmsaraujo.dev
description: >-
  Hi 👋<br />I'm Fábio, a Software Engineer from Portugal 🇵🇹
show_downloads: false
domain: fmsaraujo.dev # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://fmsaraujo.dev # the base hostname and protocol for your site, e.g. http://example.com
twitter_username: fmsaraujo
github_username:  fmsaraujo
repository: fmsaraujo/fmsaraujo.github.io

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

github:
  repository_name: fmsaraujo.dev
  repository_url: https://fmsaraujo.dev
  owner_name: Fábio Araújo
  owner_url: https://github.com/fmsaraujo
  is_project_page: true

linkedin:
  url: https://www.linkedin.com/in/fmsaraujo/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
